# Generated by Django 5.1.2 on 2024-11-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='username',
            new_name='name',
        ),
    ]
